spring:
  application:
    name: rocketmq-demo

  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
#        out:
#          destination: out
#          content-type: application/json
#          group: test-group

        output1:
          destination: test-topic1
          content-type: application/json
          group: test-group

        output2:
          destination: test-topic2
          content-type: application/json
          group: test-group

#        input:
#          destination: out
#          group: test-group
#          content-type: application/json

        input1:
          destination: test-topic1
          content-type: text/plain
          group: test-group
          consumer:
            orderly: true

        input2:
          destination: test-topic2
          content-type: text/plain
          group: test-group
          consumer:
            orderly: false
            tags: tagStr
            concurrency: 20

  functional:
  enabled: true
server:
  port: 8888

logging:
  file:
    path: ./logs
  level:
    root: DEBUG
